spring:
  datasource:
    url: jdbc:mysql://localhost:3306/structurax_db
    username: root
    password: Mohan@1234

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

server:
  port: 8081

  